# Generated by Django 3.0.6 on 2020-05-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'WebUser',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('picture_big', models.URLField()),
                ('played', models.BooleanField()),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jukebox.WebUser')),
            ],
            options={
                'db_table': 'Track',
            },
        ),
    ]
